### ISSUE TITLE
Coloque esse teu projeto mesclado ao do WPS-Community

### ISSUE THREAD

**Issue by uzielweb** [biglinux/wps-office-mui-pt#1]
Veja como fazer aqui: https://github.com/biglinux/wps-office-mui-pt
O pt-BR está parado há 4 anos lá
Os links da KAIANA não funcionam mais.
Poderia postar aqui nos releases os deb que por acaso fizeste?

**Comment by bigbruno** [comment]
http://biglinux.c3sl.ufpr.br/packages/unstable/main/wps-office-mui-pt_2.0.0-2biglinux1_all.deb
