### ISSUE TITLE
Tradução WPS 2019

### ISSUE THREAD

**Issue by alexwender1** [biglinux/wps-office-mui-pt#2]
Você está mantendo a tradução do WPS?

A página do WPS Community (assim como no Git) está totalmente parada (para não falar abandonada). É difícil saber se há alguém na suposta comunidade WPS.

Ontem, foi lançado a versão 2019... o seu pacote de tradução funcionou! Não tive tempo de olhar se tudo estava traduzido, mas a princípio sim. O dicionário eu peguei do site deles... Não sei se você fez alguma modificação na versão aqui do Git, houve modificação?

**Comment by bigbruno** [comment]
Não estou traduzindo, nem fiz parte da tradução, aqui está o original: https://github.com/biglinux/core-apps/tree/master/wps-office-mui-pt-br

**Comment by bigbruno** [comment]
Não traduzi nem fiz parte da tradução, quem estava a frente dessa tradução era ele: https://github.com/pepaulo

**Comment by alexwender1** [comment]
Muito obrigado pelo direcionamento!
